### ISSUE TITLE
Path replacement is broken does not work as intended

### ISSUE THREAD

**Issue by TheOneKevin** [Rsl1122/PluginFolderSwapper#2]
On some Linux systems, `'%serverfolder%//essentials'` works whereas `'%serverfolder%/essentials'` does not. Seeing the source, you are simply finding and replacing strings, and then joining the resultant strings together. I think using Java path operations should resolve this issue.

**Comment by AuroraLS3** [comment]
That is true.

I shall blame this on my inexperience at the time of making this plugin.

**Comment by AuroraLS3** [comment]
Should be fixed in 1.3.0
