### ISSUE TITLE
Plugin not working at all on Linux.

### ISSUE THREAD

**Issue by notsatvrn** [Rsl1122/PluginFolderSwapper#3]
Using Skynode for hosting if that helps.

Config:

Check_for_updates: true
PluginPaths:
- '/home/container/plugins/QOL/'

Doesn't find any of the plugins in that folder, and I have verified that it is the proper location.

**Comment by DavidForge** [comment]
This is related to my issue I think so I will write my info with that here.

I think is the same problem because I dont know why but it dont work for me too, dont detect the plugins, I tested in two ways for put the directory.
The console: https://pastebin.com/sUK6mRTC

**Comment by DavidForge** [comment]
I tested the latest version but for me the plugin is not working yet.

Some idea?

My console: https://pastebin.com/sJhSC24i

**Comment by AuroraLS3** [comment]
Have you tried putting in the full path to the folder? @Elguerrero11

**Comment by DavidForge** [comment]
Yes, is already I think, look:

I tested:

- root/HD/CP3/plugins/Utilidades
- root/HD/CP3/plugins/Utilidades/HPing-1.0.jar

**Comment by AuroraLS3** [comment]
Have you put / in front of root?

**Comment by DavidForge** [comment]
Not, I will test wait.

**Comment by DavidForge** [comment]
Dont look that work.

Only load the plugins that is in original plugins folder.

https://pastebin.com/ekhhVH2z

**Comment by AuroraLS3** [comment]
Does it work with 1.2.3?

**Comment by DavidForge** [comment]
I suppose you want to say 1.3.2 and not, was not working too.

**Comment by notsatvrn** [comment]
Still doesn't work (1.3.3)

**Comment by Greazi-Times** [comment]
Same problem here.

I have setup everything but it doesn't load my plugins.

Server version: Paper version git-Paper-575 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
System Info: Java 11 (OpenJDK 64-Bit Server VM 11.0.10+9) Host: Linux 4.19.0-10-amd64 (amd64)

**Comment by BiggestPotato111** [comment]
Still isnt working in 1.3.3 for me either. I have a Ubuntu machine

**Comment by BiggestPotato111** [comment]
Bump. Is the developer still active?

**Comment by AuroraLS3** [comment]
> Is the developer still active?

Yes but this plugin is not a priority for me. I've been rather busy with other stuff recently.

**Comment by BiggestPotato111** [comment]
> > Is the developer still active?
> 
> Yes but this plugin is not a priority for me. I've been rather busy with other stuff recently.

Alright, thank you for responding! This seems like a great plugin, and ill be looking forward to you getting around to it.

**Comment by AuroraLS3** [comment]
Fixed in 1.3.4 https://www.spigotmc.org/resources/plugin-folder-swapper.34336/update?update=445673
